on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: deploy to branch
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '19'
      - name: Clone Backend
        run: git clone https://github.com/TeamCoderX/joinstu-backend.git
      - name: Merge main -> deploy
        working-directory: ./joinstu-backend
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: deploy
        